#!/usr/bin/env bash

set -ex

cd build

if [ -e firmware ]; then
   cd firmware
   git clean -dfx .
   git checkout -- .
   cd ..
else
   git clone --depth=1 https://github.com/raspberrypi/firmware
fi

cd firmware/boot

rm {*.dtb,*.img}

touch ../../.firmware
