#!/usr/bin/env bash

set -ex

if [ -e build/linux ]; then
   rm -r build/linux
fi

cd build/linux-src

mkdir -p ../linux/boot ../linux/usr/bin ../linux/opt

cp arch/arm/boot/Image ../linux/boot/kernel.img
cp arch/arm/boot/dts/bcm2708-rpi-zero-w.dtb ../linux/boot
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_MOD_PATH=$(dirname $PWD)/linux modules_install
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_HDR_PATH=$(dirname $PWD)/linux/usr headers_install

cd ..

GOOS=linux GOARCH=arm go build -o ./linux/usr/bin/pi64-update github.com/bamarni/pi64/cmd/pi64-update
GOOS=linux GOARCH=arm go build -o ./linux/usr/bin/pi64-config github.com/bamarni/pi64/cmd/pi64-config

mkdir linux/opt/vc
cp -R userland/build/* linux/opt/vc
mv linux/opt/vc/bin/* linux/usr/bin/

cp -R firmware/boot/* linux/boot

touch .linux
