#!/usr/bin/env bash

set -ex

mkdir -p build && cd build

if [ -e linux-src ]; then
   cd linux-src
   git clean -dff .
   git checkout -- .
   cd ..
else
   git clone --depth=1 -b rpi-4.14.y https://github.com/raspberrypi/linux.git linux-src
fi

cd linux-src

cp ../../make/kernel-config.txt ./.config

make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- olddefconfig

make -j $(nproc) ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-

touch ../.linux-src
