#!/usr/bin/env bash

set -ex

mkdir -p build && cd build

if [ -e linux-src ]; then
   cd linux-src
   git clean -dff .
   git checkout -- .
   cd ..
else
   git clone --depth=1 -b rpi-4.20.y https://github.com/raspberrypi/linux.git linux-src
fi

cd linux-src

# cp ../../make/kernel-config.txt ./.config

make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcmrpi3_defconfig

make -j $(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-

touch ../.linux-src
