#!/usr/bin/env bash

set -ex

mkdir -p build && cd build

git clone --depth=1 https://github.com/raspberrypi/userland

rm -rf ./userland/build && mkdir -p ./userland/build

cd ./userland/build

cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_BUILD_TYPE=release -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_ASM_COMPILER=arm-linux-gnueabihf-gcc -DVIDEOCORE_BUILD_DIR=/opt/vc ../

make -j $(nproc)
